/// Flutter icons QRCodeIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QRCodeIcons
///      fonts:
///       - asset: fonts/QRCodeIcons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class QRCodeIcons {
  QRCodeIcons._();

  static const _kFontFam = 'QRCodeIcons';

  static const IconData qrcode = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData qr_scan = const IconData(0xe801, fontFamily: _kFontFam);
}
